# Generated by Django 5.2.9 on 2025-12-26 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FEDERAL', 'Federal'), ('ESTADUAL', 'Estadual'), ('EMENDA_SAUDE', 'Emenda (Saúde)'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('numero_indicacao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nº da Indicação/Emenda')),
                ('numero_proposta', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nº da Proposta')),
                ('numero_convenio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nº do Convênio/Instrumento')),
                ('parlamentar_nome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Parlamentar')),
                ('orgao_concedente', models.CharField(max_length=200, verbose_name='Órgão concedente')),
                ('objeto', models.TextField()),
                ('valor_repasse', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_contrapartida', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('foi_licitado', models.BooleanField(default=False)),
                ('modalidade', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_processo_licitatorio', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('CAPTACAO', 'Em captação'), ('PROPOSTA', 'Proposta'), ('CONVENIADO', 'Conveniado'), ('EXECUCAO', 'Em execução'), ('PRESTACAO', 'Prestação de contas'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PROPOSTA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['vigencia_fim', 'orgao_concedente'],
            },
        ),
    ]
