# Generated by Django 5.2.9 on 2025-12-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='repasse_recebido',
            field=models.BooleanField(default=False, verbose_name='Repasse recebido (Órgão já pagou?)'),
        ),
    ]
