# Generated by Django 5.2.9 on 2025-12-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=14)),
                ('numero_empenho', models.CharField(blank=True, max_length=80, null=True)),
                ('numero_ob', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nº Ordem Bancária')),
                ('numero_nf', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nº Nota Fiscal')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='contratos.contrato')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
