# Generated by Django 5.2.9 on 2025-12-26 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=220)),
                ('nome_fantasia', models.CharField(blank=True, max_length=220, null=True)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=80)),
                ('numero_processo', models.CharField(blank=True, max_length=80, null=True)),
                ('objeto_contratado', models.TextField()),
                ('valor_contratado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('RESCINDIDO', 'Rescindido')], default='ATIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='convenios.convenio')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAZO', 'Prazo'), ('VALOR', 'Valor'), ('QUANTITATIVO', 'Quantitativo'), ('REAJUSTE', 'Reajuste'), ('SUPRESSAO', 'Supressão')], max_length=20)),
                ('numero_aditivo', models.CharField(max_length=80)),
                ('data', models.DateField()),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_supressao', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dias_prazo', models.IntegerField(default=0)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contratos.contrato')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
